### ISSUE TITLE
`:members:` with a list is not respected

### ISSUE THREAD

**Issue by Kodiologist** [hylang/sphinxcontrib-hydomain#12]
For example, if in `index.rst` at https://github.com/hylang/hyrule/commit/22a1a6bdccb782888d3166f08a96e1e7b8e23cf2 I change

```
.. hy:automodule:: hyrule.anaphoric
  :members:
```

to

```
.. hy:automodule:: hyrule.anaphoric
  :members: ap-each
```

, Sphinx will still document everything in the module.

**Comment by allison-casey** [comment]
closed in 131d45a

**Comment by Kodiologist** [comment]
I'm confused. What's the right way to get that commit? It's not in master.

**Comment by allison-casey** [comment]
i fell for the classic blunder of not checking my remotes. should be good now
